Migrate to mongodb phase 2
TODO:
- Fix when running /sweep causes
TypeError: 'NoneType' object is not subscriptable

- Optimize initialization step for performance

- Check regressions when changing tools