Aiosqlite to mongo (#10)
New features in this version so far:
- Move from SQLite to MongoDB using Motor
  - `CHAT_HISTORY_DB` is now `MONGO_DB_URL` (connection string)
- Add `show_stats` parameter in `/ask` command to show the chat conversation turn counts and the models used (off by default)
- Deprecate JSON mode, users must instruct the model to format its responses to JSON
- Refactoring some code
   - Function calling code is reduced / Tool definitions and functions are refactored to simply import them as modules and parse `Tool` class and its properties instead of using separate tool/function registration and use `_callable` syntax and mandatory convention to call functions.
      - When calling tools, the interstitial now displays a human readable name instead of the function name
   - Inherit / merge `chat_mgmt.py` and `genai.py` to simply `chat.py` (controls) which inherits from `generative.py` (LLM generation) so the generative module is now responsible for database connection and LLM lifecycle. It is still a cog/discord command where it contains `/ask`
 - Update docs (WIP)
 - `prompt_history` is now a counter for how many chat interactions was made instead of counting arrays arrays of prompt which is a privacy implication if one views the database to check chat length based on turns

* migrate to mongodb phase 1:

Get and set works but theres so many things to unravel, line 293 isn't even finished

* Revert "migrate to mongodb phase 1:"

This reverts commit 78964d2daf68ccce132426d302a09c0ffd18e277.

* Migrate to mongodb phase 2

TODO:
- Fix when running /sweep causes
TypeError: 'NoneType' object is not subscriptable

- Optimize initialization step for performance

- Check regressions when changing tools

* "thread"

* reaching goal to keep the connection stateful to improve performance

* improvements

TODO: check tool calls

* I accomplished things so far

- Fix tools not setting correctly
- Parameter-based guild id instead of initializing it
- Make list of models as a class

TODO:
- Optimize memory footprint
- MongoDB initialization step at top level (main) instead of twice

* Attempt to optimize more things

- Tools list is now under the class level like models list
- Chat history initialization is now under main.py so the instances is shared

TODO:
- Async tests

* Stuff

* Update system prompt

* Indexing

* MONGO_DB_URL instead of CHAT_HISTORY_URL

* Change references from SQLite to MongoDB

* GenAI configuration and system prompt/config init must be at init class level so run-once operations don't get called twice

* rename

* Add dev.env value to store database under different name

Add "show_stats" and do not print the stats by default

Init history at cog init level

* Typo

* Tools: use much more cleaner way of calling tools

Eliminates extra classes

Add UI interstitial name for the Tool

* Inherit / merge gemini chat classes so all the state are shared and avoid some performance issues and regressions

* update tools and docs

* update docs

* Use prompt_count instead of prompt_history to check the length of chat

Also privacy issue if the prompts are stored in MongoDB which can be viewed with tools like Data Explorer

* Update docs

* Update depedency doc

Emphasize serverless lavalink

* stuff

* update tools doc to clarify naming conventions

* Some people are stubborn and curious

* Pls help lol OCD at readme

* update show_stats to verbose_logs parameter

* Add tool_config

* fixes to tools and docs

* remove incorrect references